import test from "node:test";
import assert from "node:assert/strict";
import { CONFIG } from "../src/js/core/config.js";
import { preferences, runtime, replacePreferences, resolveSettings, normalizeOrbDef } from "../src/js/core/preferences.js";
import { state } from "../src/js/core/state.js";
import { createOrbEditorUi, readBulkOrbValue } from "../src/js/ui/orb-editor.js";

function element(tag="div") { const listeners=new Map(); return { tagName:tag.toUpperCase(), type:"", dataset:{}, children:[], value:"", textContent:"", disabled:false, checked:false, indeterminate:false, attributes:{}, open:false,
 addEventListener(n,f){const a=listeners.get(n)||[];a.push(f);listeners.set(n,a)}, dispatch(n){for(const f of listeners.get(n)||[])f({target:this})}, listenerCount(n){return (listeners.get(n)||[]).length}, append(...c){for(const x of c){this.children=this.children.filter(y=>y!==x);this.children.push(x)}}, appendChild(c){this.children=this.children.filter(y=>y!==c);this.children.push(c);return c}, remove(){this.removed=true}, focus(){document.activeElement=this}, scrollIntoView(){}, setAttribute(n,v){this.attributes[n]=String(v)}, getAttribute(n){return this.attributes[n]}, querySelector(){return null} }; }
function ui() { const result={orbEditorList:element(),simStatus:element()}; for(const [n,t] of [["chkLines","checkbox"],["rngNumLines","range"],["selLineColorMode","select"],["rngEmit","range"],["rngSizeMax","range"],["rngSizeMin","range"],["rngSizeToMin","range"],["rngTTL","range"],["rngOverlap","range"],["rngOmega","range"],["rngWfDisp","range"],["rngMinRad","range"],["rngMaxRad","range"]]) { result[n]=element(); result[n].type=t; result[`val${n.replace(/^(chk|rng|sel)/,"")}`]=element(); } return result; }
function orb(id){return {...structuredClone(CONFIG.defaults.orbs[0]),id};}
function harness(ids){ const old=structuredClone(preferences), oldDoc=globalThis.document; globalThis.document={activeElement:null,createElement:element}; replacePreferences({...structuredClone(CONFIG.defaults),orbs:ids.map(orb)});resolveSettings();const view=ui(),calls=[];const editor=createOrbEditorUi({ui:view,commitOrbChangeById:(...x)=>calls.push(x),commitPreferences:(...x)=>calls.push(x),showStatus:()=>{}});return {old,oldDoc,view,calls,editor,restore(){replacePreferences(old);resolveSettings();globalThis.document=oldDoc}}; }

test("dynamic editor supports zero, one, and N Orbs and disables bulk at zero",()=>{for(const ids of [[],["A"],["A","B","C","D","E","F","G"]]){const h=harness(ids);try{h.editor.init();assert.equal(h.editor.refresh().size,ids.length);assert.equal(h.view.orbEditorList.children.length,ids.length);assert.equal(h.view.rngEmit.disabled,ids.length===0);assert.equal(h.view.simStatus.textContent,ids.length?`${ids.length} Orb${ids.length===1?"":"s"} in scene`:"No Orbs in scene");}finally{h.restore()}}});

test("editor reconciliation retains roots by ID, reorders nodes, and replaces only structural changes",()=>{const h=harness(["A","B","C"]);try{h.editor.init();const roots=new Map(["A","B","C"].map(id=>[id,h.editor.getController(id).root]));h.view.orbEditorList.children=[];h.editor.refresh();assert.equal(h.editor.getController("A").root,roots.get("A"));preferences.orbs=[preferences.orbs[2],preferences.orbs[0],preferences.orbs[1]];resolveSettings();h.view.orbEditorList.children=[];h.editor.refresh();assert.deepEqual(h.view.orbEditorList.children.map(n=>n.dataset.orbId),["C","A","B"]);preferences.orbs=[preferences.orbs[1],orb("D"),preferences.orbs[2]];resolveSettings();h.view.orbEditorList.children=[];h.editor.refresh();assert.equal(h.editor.getController("A").root,roots.get("A"));assert.equal(h.editor.getController("B").root,roots.get("B"));assert.equal(h.editor.getController("C"),undefined);assert.ok(h.editor.getController("D"));}finally{h.restore()}});

test("generated controls commit by persistent ID after reorder and focusOrb is ID based",()=>{const h=harness(["A","B","C"]);try{h.editor.init();preferences.orbs=[preferences.orbs[2],preferences.orbs[0],preferences.orbs[1]];resolveSettings();h.editor.refresh();const a=h.editor.getController("A");a.chan.value="R";a.chan.dispatch("change");assert.deepEqual(h.calls[0].slice(0,1),["A"]);assert.equal(h.editor.focusOrb("A"),true);assert.equal(document.activeElement,a.summary);assert.equal(h.editor.focusOrb("missing"),false);}finally{h.restore()}});

test("bulk helper keeps mixed and zero semantics",()=>{assert.deepEqual(readBulkOrbValue([],"particles","emitPerSecond"),{available:false,mixed:false,value:undefined});assert.equal(readBulkOrbValue([orb("A"),orb("B")],"particles","emitPerSecond").mixed,false);});

test("refresh skips unchanged controller and picker work but invalidates on settings and band-edge replacement",()=>{const h=harness(["A"]);const oldEdges=state.bands.lowHz;let appends=0,syncs=0;const append=h.view.orbEditorList.appendChild.bind(h.view.orbEditorList);h.view.orbEditorList.appendChild=node=>{appends++;return append(node)};h.editor=createOrbEditorUi({ui:h.view,commitOrbChangeById:()=>{},commitPreferences:()=>{},showStatus:()=>{},createBandPicker:()=>({sync(){syncs++}})});try{h.editor.init();assert.deepEqual({appends,syncs},{appends:1,syncs:1});h.editor.refresh(runtime.settings);h.editor.refresh(runtime.settings);assert.deepEqual({appends,syncs},{appends:1,syncs:1});resolveSettings();h.editor.refresh(runtime.settings);assert.deepEqual({appends,syncs},{appends:2,syncs:2});h.editor.refresh(runtime.settings);assert.deepEqual({appends,syncs},{appends:2,syncs:2});state.bands.lowHz=[...oldEdges];h.editor.refresh(runtime.settings);assert.deepEqual({appends,syncs},{appends:3,syncs:3});h.editor.refresh(runtime.settings);assert.deepEqual({appends,syncs},{appends:3,syncs:3});}finally{state.bands.lowHz=oldEdges;h.restore()}});

test("every schema-10 Orb setting has a generated writable control",()=>{const h=harness(["unsafe id #1"]);try{h.editor.init();const c=h.editor.getController("unsafe id #1");for(const key of ["chan","bands","chir","phase","hue","color","x","y","speed","minRadius","maxRadius","waveform","emit","sizeMax","sizeMin","decay","ttl","overlap","lines","numLines","lineAlpha","lineWidth","lineColor"])assert.ok(c[key],key);const ids=[c.chan,c.bands,c.chir,c.phase,c.hue,c.color,c.x,c.y,c.speed,c.minRadius,c.maxRadius,c.waveform,c.emit,c.sizeMax,c.sizeMin,c.decay,c.ttl,c.overlap,c.lines,c.numLines,c.lineAlpha,c.lineWidth,c.lineColor].map(x=>x.id);assert.equal(new Set(ids).size,ids.length);assert.ok(ids.every(id=>!id.includes("unsafe id #1")));}finally{h.restore()}});

test("phase is presented in degrees and commits radians by stable ID",()=>{const h=harness(["A","B","C"]);try{preferences.orbs[0].startAngleRad=Math.PI/2;resolveSettings();h.editor.init();assert.equal(h.editor.getController("A").phaseValue.textContent,"90°");preferences.orbs=[preferences.orbs[2],preferences.orbs[0],preferences.orbs[1]];resolveSettings();h.editor.refresh();const a=h.editor.getController("A");a.phase.value=String(Math.PI);a.phase.dispatch("input");assert.equal(preferences.orbs.find(o=>o.id==="A").startAngleRad,Math.PI);assert.equal(preferences.orbs.find(o=>o.id==="B").startAngleRad,CONFIG.defaults.orbs[0].startAngleRad);assert.equal(h.calls.at(-1)[0],"A");}finally{h.restore()}});

test("nested controls remain independent and canonical normalization refreshes their values",()=>{const h=harness(["A","B"]);try{h.editor=createOrbEditorUi({ui:h.view,showStatus:()=>{},commitPreferences:()=>{},commitOrbChangeById(id){const i=preferences.orbs.findIndex(o=>o.id===id);preferences.orbs[i]=normalizeOrbDef(preferences.orbs[i],CONFIG.defaults.orbs[0]);resolveSettings();}});h.editor.init();const b=h.editor.getController("B");b.speed.value="2.25";b.speed.dispatch("input");b.lineAlpha.value="0.44";b.lineAlpha.dispatch("input");b.lineWidth.value="5";b.lineWidth.dispatch("input");b.sizeMax.value="2";b.sizeMax.dispatch("input");b.sizeMin.value="5";b.sizeMin.dispatch("input");b.decay.value="8";b.decay.dispatch("input");b.ttl.value="1";b.ttl.dispatch("input");h.editor.refresh();const a=preferences.orbs.find(o=>o.id==="A"), normalized=preferences.orbs.find(o=>o.id==="B");assert.equal(a.motion.angularSpeedRadPerSec,CONFIG.defaults.orbs[0].motion.angularSpeedRadPerSec);assert.equal(normalized.motion.angularSpeedRadPerSec,2.25);assert.equal(normalized.trace.lineAlpha,.44);assert.equal(normalized.trace.lineWidthPx,5);assert.equal(normalized.particles.sizeMinPx,2);assert.equal(normalized.particles.ttlSec,8);assert.equal(b.sizeMin.value,"2");assert.equal(b.ttl.value,"8");}finally{h.restore()}});

test("ten arbitrary-ID Orb cards retain independent phase and nested values",()=>{const ids=Array.from({length:10},(_,i)=>`scene orb ${i*7}`),h=harness(ids);try{preferences.orbs.forEach((o,i)=>{o.startAngleRad=(i%2)*Math.PI;o.motion.angularSpeedRadPerSec=.2+i*.1;o.bandIds=[i];});resolveSettings();h.editor.init();assert.equal(h.editor.refresh().size,10);assert.equal(new Set(ids.map(id=>h.editor.getController(id).phase.id)).size,10);const target=h.editor.getController(ids[7]);target.ttl.value="12";target.ttl.dispatch("input");assert.equal(preferences.orbs[7].particles.ttlSec,12);assert.equal(preferences.orbs[6].particles.ttlSec,CONFIG.defaults.orbs[0].particles.ttlSec);}finally{h.restore()}});
